-
  branches:
    only:
      - production
  configuration: Release
  platform: Any CPU
  deploy:
    - provider: Environment
      name: RPThreadTracker-Production
  build:
    project: RPThreadTracker.sln
    publish_wap: true
    verbosity: quiet
  before_build:
    - ps: nuget restore RPThreadTracker.sln -Verbosity Quiet
  environment:
    nodejs_version: "6"
  install:
    - ps: Install-Product node $env:nodejs_version
    - ps: cd RPThreadTracker/application
    - ps: npm install
    - ps: cd ../../
  test_script:
    - cd RPThreadTracker/application
    - node --version
    - npm --version
    - npm run eslint
    - cd ../../
    - nunit3-console RPThreadTrackerTests/RPThreadTrackerTests.csproj --result=nunit-results.xml;format=AppVeyor --config=Release
-
  branches:
    only:
      - development
  configuration: Staging
  platform: Any CPU
  deploy:
    - provider: Environment
      name: RPThreadTracker-Staging
  build:
    project: RPThreadTracker.sln
    publish_wap: true
    verbosity: quiet
  before_build:
    - ps: nuget restore RPThreadTracker.sln -Verbosity Quiet
  environment:
    nodejs_version: "6"
  install:
    - ps: Install-Product node $env:nodejs_version
    - ps: cd RPThreadTracker/application
    - ps: npm install
    - ps: cd ../../
  test_script:
    - cd RPThreadTracker/application
    - node --version
    - npm --version
    - npm run eslint
    - cd ../../
    - nunit3-console RPThreadTrackerTests/RPThreadTrackerTests.csproj --result=nunit-results.xml;format=AppVeyor --config=Staging
-
  branches:
    only:
      - testing
  configuration: Staging
  platform: Any CPU
  deploy:
    - provider: Environment
      name: RPThreadTracker-QA
  build:
    project: RPThreadTracker.sln
    publish_wap: true
    verbosity: quiet
  before_build:
    - ps: nuget restore RPThreadTracker.sln -Verbosity Quiet
  environment:
    nodejs_version: "6"
  install:
    - ps: Install-Product node $env:nodejs_version
    - ps: cd RPThreadTracker/application
    - ps: npm install
    - ps: cd ../../
  test_script:
    - cd RPThreadTracker/application
    - node --version
    - npm --version
    - npm run eslint
    - cd ../../
    - nunit3-console RPThreadTrackerTests/RPThreadTrackerTests.csproj --result=nunit-results.xml;format=AppVeyor --config=Staging
