build:
  project: RPThreadTracker.sln
  publish_wap: true
before_build:
  - ps: nuget restore RPThreadTracker.sln
environment:
  nodejs_version: "6"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - npm run eslint