build:
  project: RPThreadTracker.sln
  publish_wap: true
before_build:
  - ps: nuget restore RPThreadTracker.sln
environment:
  nodejs_version: "6"
install:
  - ps: Install-Product node $env:nodejs_version
  - ps: cd RPThreadTracker/application
  - ps: npm install
  - ps: cd ../../
test_script:
  - cd RPThreadTracker/application
  - node --version
  - npm --version
  - npm run eslint
  - cd ../../