namespace RPThreadTracker.Infrastructure.Services
{
	using System;
	using System.IO;
	using System.Linq;
	using System.Security.Claims;
	using System.Text;
	using System.Threading.Tasks;
	using Interfaces;
	using Models.DomainModels.Account;
	using Models.DomainModels.Users;
	using WebMatrix.WebData;

	/// <inheritdoc cref="IWebSecurityService"/>
	public class WebSecurityService : IWebSecurityService
	{
		/// <inheritdoc cref="IWebSecurityService"/>
		public bool ChangePassword(string username, string oldPassword, string newPassword)
		{
			return WebSecurity.ChangePassword(username, oldPassword, newPassword);
		}

		/// <inheritdoc cref="IWebSecurityService"/>
		public void CreateAccount(string username, string password, string email, IRepository<User> userProfileRepository)
		{
			WebSecurity.CreateUserAndAccount(username, password);
			var profile = new User
			{
				UserId = WebSecurity.GetUserId(username),
				UserName = username,
				Email = email,
				ShowDashboardThreadDistribution = true
			};
			userProfileRepository.Update(profile.UserId, profile);
		}

		/// <inheritdoc cref="IWebSecurityService"/>
		public string GeneratePasswordResetToken(User user)
		{
			return WebSecurity.GeneratePasswordResetToken(user.UserName);
		}

		/// <inheritdoc cref="IWebSecurityService"/>
		public User GetCurrentUserFromIdentity(ClaimsIdentity claimsIdentity, IRepository<User> userProfileRepository)
		{
			var claim = claimsIdentity?.Claims.FirstOrDefault(c => c.Type == "userId");
			if (claim == null)
			{
				return null;
			}
			var userId = int.Parse(claim.Value);
			return userProfileRepository.GetSingle(u => u.UserId == userId);
		}

		/// <inheritdoc cref="IWebSecurityService"/>
		public int? GetCurrentUserIdFromIdentity(ClaimsIdentity claimsIdentity)
		{
			var claim = claimsIdentity?.Claims.FirstOrDefault(c => c.Type == "userId");
			if (claim == null)
			{
				return null;
			}
			var userId = int.Parse(claim.Value);
			return userId;
		}

		/// <inheritdoc cref="IWebSecurityService"/>
		public int? GetUserIdByUsernameAndPassword(string username, string password, IRepository<User> userProfileRepository)
		{
			var userExistsWithUsername = System.Web.Security.Membership.Provider.ValidateUser(username, password);
			if (userExistsWithUsername)
			{
				return WebSecurity.GetUserId(username);
			}
			var userByEmail = userProfileRepository.GetSingle(u => u.Email == username);
			if (userByEmail == null)
			{
				return null;
			}
			var usernameFromEmailIsValid = System.Web.Security.Membership.Provider.ValidateUser(userByEmail.UserName, password);
			return usernameFromEmailIsValid ? WebSecurity.GetUserId(userByEmail.UserName) : (int?)null;
		}

		/// <inheritdoc cref="IWebSecurityService"/>
		public string ResetPassword(string resetToken)
		{
			var newPassword = GenerateRandomPassword(6);
			var response = WebSecurity.ResetPassword(resetToken, newPassword);
			if (!response)
			{
				throw new InvalidOperationException();
			}
			return newPassword;
		}

		/// <inheritdoc cref="IWebSecurityService"/>
		public string GenerateRandomPassword(int length)
		{
			const string allowedChars = "abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNOPQRSTUVWXYZ0123456789!@$?_-*&#+";
			var chars = new char[length];
			var rd = new Random();
			for (var i = 0; i < length; i++)
			{
				chars[i] = allowedChars[rd.Next(0, allowedChars.Length)];
			}
			return new string(chars);
		}

		/// <inheritdoc cref="IWebSecurityService"/>
		public async Task SendForgotPasswordEmail(User user, string token, IRepository<Membership> webpagesMembershipRepository, IEmailService emailService)
		{
			var isValidToken = IsValidToken(user, token, webpagesMembershipRepository);
			if (!isValidToken)
			{
				throw new InvalidDataException();
			}
			var newPassword = ResetPassword(token);
			await SendTemporaryPasswordEmail(user, newPassword, emailService);
		}

		private static bool IsValidToken(User user, string resetToken, IRepository<Membership> webpagesMembershipRepository)
		{
			var record = webpagesMembershipRepository.Get(m => m.UserId == user.UserId && m.PasswordVerificationToken == resetToken);
			return record.Any();
		}

		private static async Task SendTemporaryPasswordEmail(User user, string newPassword, IEmailService emailService)
		{
			const string subject = "RPThreadTracker ~ New Temporary Password";
			var bodyBuilder = new StringBuilder();
			bodyBuilder.Append("<p>Hello,</p>");
			bodyBuilder.Append("<p>Below is your autogenerated temporary password for RPThreadTracker:</p>");
			bodyBuilder.Append("<p>" + newPassword + "</p>");
			bodyBuilder.Append("<p>Use this password to log into the tracker; be sure to change your password to something secure once you are logged in.</p>");
			bodyBuilder.Append("<p>Thanks, and have a great day!</p>");
			bodyBuilder.Append("<p>~Tracker-mun</p>");
			var body = bodyBuilder.ToString();
			await emailService.SendEmail(user.Email, subject, body);
		}
	}
}