//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPThreadTracker.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserThread
    {
        public UserThread()
        {
            this.UserThreadTags = new HashSet<UserThreadTag>();
        }
    
        public int UserThreadId { get; set; }
        public int UserBlogId { get; set; }
        public string PostId { get; set; }
        public string UserTitle { get; set; }
        public string WatchedShortname { get; set; }
        public bool IsArchived { get; set; }
    
        public virtual UserBlog UserBlog { get; set; }
        public virtual ICollection<UserThreadTag> UserThreadTags { get; set; }
    }
}
