//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TumblrThreadTracker.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserThreadTag
    {
        public int TagID { get; set; }
        public string TagText { get; set; }
        public Nullable<int> UserThreadID { get; set; }
    
        public virtual UserThread UserThread { get; set; }
    }
}
