//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPThreadTracker.Infrastructure.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RPThreadTrackerEntities : DbContext
    {
        public RPThreadTrackerEntities()
            : base("name=RPThreadTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserBlog> UserBlogs { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
        public virtual DbSet<UserThread> UserThreads { get; set; }
        public virtual DbSet<UserThreadTag> UserThreadTags { get; set; }
        public virtual DbSet<WebpagesMembership> WebpagesMemberships { get; set; }
    }
}
