//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPThreadTracker.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBlog
    {
        public UserBlog()
        {
            UserThreads = new HashSet<UserThread>();
        }
    
        public int UserBlogId { get; set; }
        public int UserId { get; set; }
        public string BlogShortname { get; set; }
        public bool OnHiatus { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<UserThread> UserThreads { get; set; }
    }
}
